routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'index','uses' => 'IndexController@index']);
Route::get('/pagseguro/session', ['as' => 'index','uses' => 'PagseguroController.php@session']);
Route::post('/pagseguro/notification', ['as' => 'checkout.notification','uses' => 'PagseguroController@checkoutNotification']);

Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'postlogin','uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);
Route::get('register', ['as'=>'register','uses'=>'Auth\RegisterController@showregister']);
Route::post('register', ['as'=>'postregister','uses' => 'Auth\RegisterController@register']);
Route::get('password/remind', ['as'=>'password.remind','uses'=>'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/remind', ['as'=>'send.password.remind','uses'=>'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as'=>'password.reset', 'uses'=>'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as'=>'password.update','uses'=>'Auth\ResetPasswordController@reset']);

Route::get('cidades/{estado_id}', ['as' => 'cidades','uses' => 'CidadesController@index']);
Route::get('categoria/{categoria_id}', ['as' => 'categoria','uses' => 'CategoriasController@index']);

Route::get('artistas', ['as' => 'artist.index','uses' => 'ArtistsController@index']);
Route::get('artistas/{id}', ['as' => 'artist.show','uses' => 'ArtistsController@show']);
Route::get('profissionais', ['as' => 'professional.index','uses' => 'ProfessionalsController@index']);
Route::get('profissionais/{id}', ['as' => 'professional.show','uses' => 'ProfessionalsController@show']);

Route::group(['middleware' => 'auth'], function() {
    Route::get('anuncio', ['as' => 'advertisement.index','uses' => 'AdvertisementController@create']);
    Route::post('anuncio', ['as' => 'advertisement.post','uses' => 'AdvertisementController@store']);
    Route::get('anuncio/{id}', ['as' => 'advertisement.edit','uses' => 'AdvertisementController@back']);
    Route::post('anuncio/{id}', ['as' => 'advertisement.update','uses' => 'AdvertisementController@update']);
    Route::get('anuncio/{id}/plano', ['as' => 'advertisement.plan','uses' => 'AdvertisementController@plan']);
    Route::post('anuncio/{id}/finalizar', ['as' => 'advertisement.finish','uses' => 'AdvertisementController@choosePlan']);


    Route::post('anuncio/{id}/pagar', ['as' => 'advertisement.plan.pay','uses' => 'AdvertisementController@pagar']);
    Route::get('checkout/sucesso', ['as' => 'checkout.sucess','uses' => 'PagseguroController@checkoutSuccess']);

    Route::get('minha-conta/mensagens', ['as' => 'message.index','uses' => 'MessagesController@index']);
    Route::get('minha-conta/mensagens/{id}', ['as' => 'message.show','uses' => 'MessagesController@show']);
    Route::post('mensagens/{id}/send', ['as' => 'message.send','uses' => 'MessagesController@send']);
    Route::get('minha-conta/mensagens/{id}/excluir', ['as' => 'conversation.delete','uses' => 'MessagesController@delete']);

    Route::post('avaliar/artista/{id}', ['as' => 'review.artist.store','uses' => 'AdvertisementController@storeReviewArtista']);
    Route::post('avaliar/profissional/{id}', ['as' => 'review.professional.store','uses' => 'AdvertisementController@storeReviewProfessional']);
    Route::get('avaliacao/{id}/excluir', ['as' => 'review.delete','uses' => 'AdvertisementController@deleteReview']);

    Route::get('minha-conta', ['as' => 'myaccount.index','uses' => 'MyAccountController@index']);
    Route::get('minha-conta/anuncios', ['as' => 'myaccount.advertisement','uses' => 'MyAccountController@advertisement']);
    Route::get('minha-conta/anuncios/{anuncio_id}/editar', ['as' => 'myaccount.advertisement.edit','uses' => 'MyAccountController@advertisementEdit']);
    Route::post('minha-conta/anuncios/{anuncio_id}/editar', ['as' => 'myaccount.advertisement.update','uses' => 'MyAccountController@advertisementUpdate']);
    Route::get('minha-conta/anuncios/{anuncio_id}/publicar', ['as' => 'myaccount.advertisement.publish','uses' => 'MyAccountController@advertisementPublish']);
    Route::post('minha-conta/anuncios/{anuncio_id}/editar/imagem', ['as' => 'myaccount.advertisement.update.image','uses' => 'MyAccountController@advertisementUpdateImage']);
    Route::get('minha-conta/anuncios/{anuncio_id}/pagar', ['as' => 'myaccount.advertisement.pay','uses' => 'MyAccountController@advertisementPay']);
    Route::get('minha-conta/anuncios/{anuncio_id}/excluir', ['as' => 'myaccount.advertisement.delete','uses' => 'MyAccountController@advertisementDelete']);
    Route::get('minha-conta/configuracoes', ['as' => 'myaccount.settings','uses' => 'MyAccountController@settings']);
    Route::post('minha-conta/configuracoes/editar', ['as' => 'myaccount.settings.update.details','uses' => 'MyAccountController@settingsupdate']);
    Route::post('minha-conta/configuracoes/editar/senha', ['as' => 'myaccount.settings.update.password','uses' => 'MyAccountController@settingsupdatepassword']);
    Route::get('minha-conta/plano', ['as' => 'myaccount.plan','uses' => 'MyAccountController@plan']);
    Route::get('minha-conta/plano/{id}/assinar', ['as' => 'myaccount.plan.subscribe','uses' => 'MyAccountController@planSubscribe']);
    Route::post('minha-conta/plano/{id}/assinar', ['as' => 'myaccount.plan.subscribe.post','uses' => 'MyAccountController@planSubscribePost']);
    Route::get('minha-conta/plano/cancelar', ['as' => 'myaccount.plan.cancel','uses' => 'MyAccountController@planCancel']);
    Route::get('minha-conta/pagamentos', ['as' => 'myaccount.payments','uses' => 'MyAccountController@payments']);
});

Route::group(['middleware' => ['auth','role:Administrador|Gerente|Proprietário'],'prefix' => 'dashboard', 'as' => 'dashboard.'], function() {
    Route::get('/', ['as' => 'index','uses' => 'Dashboard\DashboardController@index']);

    Route::get('profile', ['as' => 'profile','uses' => 'Dashboard\ProfileController@index']);
    Route::post('profile/details/update', ['as' => 'profile.update.details','uses' => 'Dashboard\ProfileController@updateDetails']);
    Route::post('profile/login-details/update', ['as' => 'profile.update.login-details','uses' => 'Dashboard\ProfileController@updateLoginDetails']);

    Route::get('user', ['as' => 'user.list','uses' => 'Dashboard\UsersController@index']);
    Route::get('user/create', ['as' => 'user.create','uses' => 'Dashboard\UsersController@create']);
    Route::post('user/create', ['as' => 'user.store','uses' => 'Dashboard\UsersController@store']);
    Route::get('user/{user_id}/edit', ['as' => 'user.edit','uses' => 'Dashboard\UsersController@edit']);
    Route::post('user/{user_id}/update/details', ['as' => 'user.update.details','uses' => 'Dashboard\UsersController@updateDetails']);
    Route::post('user/{user_id}/update/login-details', ['as' => 'user.update.login-details','uses' => 'Dashboard\UsersController@updateLoginDetails']);      //----------testar
    Route::post('user/{user_id}/update/role', ['as' => 'user.update.role','uses' => 'Dashboard\UsersController@updateRole']);
    Route::post('user/{user_id}/update/permissions', ['as' => 'user.update.permission','uses' => 'Dashboard\UsersController@updatePermissions']);
    Route::post('user/{user_id}/update/plan', ['as' => 'user.update.plan','uses' => 'Dashboard\UsersController@updatePlan']);
    Route::post('user/{user_id}/update/plan/days/add', ['as' => 'user.update.plan.days.add','uses' => 'Dashboard\UsersController@updatePlanDaysAdd']);
    Route::post('user/{user_id}/update/plan/days/remove', ['as' => 'user.update.plan.days.remove','uses' => 'Dashboard\UsersController@updatePlanDaysRemove']);
    Route::delete('user/{user_id}/delete', ['as' => 'user.delete','uses' => 'Dashboard\UsersController@destroy']);

    Route::get('advertisement', ['as' => 'advertisement.list','uses' => 'Dashboard\AdvertisementsController@index']);
    Route::get('advertisement/create', ['as' => 'advertisement.create','uses' => 'Dashboard\AdvertisementsController@create']);
    Route::post('advertisement/store', ['as' => 'advertisement.store','uses' => 'Dashboard\AdvertisementsController@store']);
    Route::get('advertisement/{advertisement_id}/edit', ['as' => 'advertisement.edit','uses' => 'Dashboard\AdvertisementsController@edit']);
    Route::post('advertisement/{advertisement_id}/update', ['as' => 'advertisement.update','uses' => 'Dashboard\AdvertisementsController@update']);
    Route::post('advertisement/{advertisement_id}/update-image', ['as' => 'advertisement.updateimage','uses' => 'Dashboard\AdvertisementsController@updateImage']);
    Route::delete('advertisement/{advertisement_id}/delete', ['as' => 'advertisement.destroy','uses' => 'Dashboard\AdvertisementsController@destroy']);

    Route::get('payment', ['as' => 'payment.list','uses' => 'Dashboard\PaymentsController@index']);
    Route::get('payment/{payment_id}', ['as' => 'payment.show','uses' => 'Dashboard\PaymentsController@show']);

    Route::get('musicstyle', ['as' => 'musicstyle.list','uses' => 'Dashboard\MusicStylesController@index']);
    Route::get('musicstyle/create', ['as' => 'musicstyle.create','uses' => 'Dashboard\MusicStylesController@create']);
    Route::post('musicstyle/store', ['as' => 'musicstyle.store','uses' => 'Dashboard\MusicStylesController@store']);
    Route::get('musicstyle/{musicstyle_id}/edit', ['as' => 'musicstyle.edit','uses' => 'Dashboard\MusicStylesController@edit']);

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Advertisement;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $advertisements = Advertisement::all();
        $monthsarray[] = date('m/Y');
        for ($i = 1; $i < 6; $i++) {
            $monthsarray[] = date('m/Y', strtotime("-$i month"));
        }
        $months='';
        foreach ($monthsarray as $m){
            $months="'".$m."'".",".$months;
        }
        $result = Advertisement::select('id', 'created_at')
            ->where("created_at",">", Carbon::now()->subMonths(6))
            ->get()
            ->groupBy(function($date) {
                return Carbon::parse($date->created_at)->format('m');
            });
        $resultarray = [];
        foreach ($result as $r){
            $resultarray[] = $r->count();
        }
        $aux = abs(count($resultarray) - 6);
        for($i = 1; $i <= $aux; $i++){
            $resultarray[] = 0;
        }
        $resultarray=array_reverse($resultarray);
        $resultarraystring='';
        foreach ($resultarray as $item){
            $resultarraystring=$resultarraystring."'".$item."'".",";
        }

        return view('dashboard.admin', compact('users','months','resultarraystring','advertisements'));
    }

}

app/Http/Controllers/Dashboard/PlansController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\dashboard\plan\CreatePlanRequest;
use App\Http\Requests\dashboard\plan\UpdatePlanRequest;
use App\Models\Plan;
use App\Models\PlanFeature;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use PagSeguroRecorrente;

class PlansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::user()->can('Visualizar planos')){
            return redirect()->back();
        }
        $peer_page = 15;
        $search = Input::get('search');
        $plans = Plan::with('subscriptions')->withCount(['subscriptions' => function (Builder $query) {
            $query->where('starts_on', '<', Carbon::now()->toDateTimeString());
            $query->where('expires_on', '>', Carbon::now());
        }]);
        if ($search <> "") {
            $plans->where(function ($q) use ($search) {
                $q->where('name', "like", "%{$search}%");
            });
        }
        $plans = $plans->paginate($peer_page);
        if ($search) {
            $plans->appends(['search' => $search]);
        }

        return view('dashboard.plan.list', compact('plans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::user()->can('Criar planos')){
            return redirect()->back();
        }


        return view('dashboard.plan.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePlanRequest $request)
    {
        if(!Auth::user()->can('Criar planos')){
            return redirect()->route('dashboard.plan.list')->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $preco = str_replace(",", ".", $request->price);
        $reference = md5(str_random(15) . microtime());
        $response = PagSeguroRecorrente::setReference($reference)
            ->sendPreApprovalRequest([
                'preApprovalName' => (string)$request->name,
                'preApprovalCharge' => 'Auto',
                'preApprovalPeriod' => 'MONTHLY',
                'preApprovalAmountPerPayment' => (string)$preco,
            ]);
        $plan = new Plan();
        $plan->name = $request->name;
        $plan->price = $request->price;
        $plan->reference = $response;
        $plan->save();

        \App\Models\PlanFeature::create([
            'plan_id' => $plan->id,
            'name' => 'qtd_ads_art',
            'limit' => $request->qtd_ads_art,
        ]);
        \App\Models\PlanFeature::create([
            'plan_id' => $plan->id,
            'name' => 'qtd_ads_pro',
            'limit' => $request->qtd_ads_pro,
        ]);


        return redirect()->route('dashboard.plan.list')->withSuccess('Plano criado com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($plan_id)
    {
        if(!Auth::user()->can('Editar planos')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $edit = true;
        $plan = Plan::find($plan_id);
        $qtd_ads_pro = PlanFeature::where('plan_id',$plan->id)->where('name','qtd_ads_pro')->first();
        $qtd_ads_art = PlanFeature::where('plan_id',$plan->id)->where('name','qtd_ads_art')->first();

        return view('dashboard.plan.edit',compact('edit', 'plan','qtd_ads_pro','qtd_ads_art'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePlanRequest $request, $plan_id)
    {
        if(!Auth::user()->can('Editar planos')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $plan = Plan::find($plan_id);
        $plan->name = $request->name;
        $plan->price = $request->price;
        $plan->save();

        $qtd_ads_pro = PlanFeature::where('plan_id',$plan->id)->where('name','qtd_ads_pro')->first();
        $qtd_ads_pro->limit = $request->qtd_ads_pro;
        $qtd_ads_pro->save();
        $qtd_ads_art = PlanFeature::where('plan_id',$plan->id)->where('name','qtd_ads_art')->first();
        $qtd_ads_art->limit = $request->qtd_ads_art;
        $qtd_ads_art->save();

        return redirect()->back()->withSuccess('Plano atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($plan_id)
    {
        if(!Auth::user()->can('Excluir planos')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $plan = Plan::find($plan_id);
        $plan->delete();

        return redirect()->route('dashboard.plan.list')->withSuccess('Plano excluido com sucesso!');
    }
}

resources/views/dashboard/plan/add.blade.php
@extends('dashboard.layouts.master')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-select.min.css') }}">
@endsection

@section('page-title', 'Adicionar plano')

@section('content_header')
    <h1>
        Criar novo plano
        <small>Detalhes do plano</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li>Planos</li>
        <li class="active">Criar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')
@can('Criar planos')
    <form action="{{route('dashboard.plan.store')}}" method="post">
        @csrf
        <div class="row">
            <div class="col-md-8">
                @include('dashboard.plan.partials.details', ['edit' => false])
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-save"></i>
                    Criar plano
                </button>
            </div>
        </div>
    </form>
@endcan
@stop

@section('js')
    <script src="{{ asset('js/bootstrap-select.min.js') }}"></script>
    <script src="{{asset('js/jquery.mask.min.js')}}"></script>
    <script>
        $('#price').mask('000,00', {reverse: true});
    </script>
@stop

resources/views/dashboard/plan/edit.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Editar plano')

@section('content_header')
    <h1>
        {{ $plan->name }}
        <small>editar detalhes do plano</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li>Planos</li>
        <li class="active">Editar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')

<div class="nav-tabs-custom">
    <!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#details" aria-controls="details" role="tab" data-toggle="tab">
            <i class="glyphicon glyphicon-th"></i>
            Detalhes
        </a>
    </li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="details">
        <div class="row">
            <div class="col-lg-8 col-md-7">
                @can('Editar planos')
                    <form action="{{route('dashboard.plan.update',$plan->id)}}" method="post">
                    @csrf
                    @include('dashboard.plan.partials.details')
                    </form>
                @endcan
            </div>
        </div>
    </div>
</div>
</div>

@stop

@section('js')
    <script src="{{asset('js/jquery.mask.min.js')}}"></script>
    <script>
        $('#price').mask('000,00', {reverse: true});
    </script>
@stop

resources/views/dashboard/plan/list.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Planos')
@section('content_header')
<h1>
    Planos
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Planos</li>
</ol>
@endsection
@section('content')
@include('partials.messages')

<div class="row tab-search">
    <div class="col-md-2 col-xs-2">
        @can('Criar planos')
            <a href="{{ route('dashboard.plan.create') }}" class="btn btn-success" id="add-user">
                <i class="glyphicon glyphicon-plus"></i>
                Adicionar plano
            </a>
        @endcan
    </div>
    <div class="col-md-5 col-xs-3"></div>
    <form method="GET" action="" accept-charset="UTF-8" id="link-form">
        <div class="col-md-3 col-xs-4">
            <div class="input-group custom-search-form">
                <input type="text" class="form-control" name="search" value="{{ app('request')->input('search') }}" placeholder="Procure por planos...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="search-users-btn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                    @if (app('request')->input('search') != '')
                        <a href="{{ route('dashboard.plan.list') }}" class="btn btn-danger" type="button" >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    @endif
                </span>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Lista de planos cadastrados</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div id="users-table-wrapper">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <th>Nome</th>
                                <th>Preço</th>
                                <th>Inscrições ativas</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            @if (count($plans))
                            @foreach ($plans as $plan)
                            <tr>
                                <td>{{ $plan->name }}</td>
                                <td>{{ $plan->price }}</td>
                                <td>{{ $plan->subscriptions_count }}</td>
                                <td class="text-center">
                                    @can('Editar planos')
                                    <a href="{{ route('dashboard.plan.edit', $plan->id) }}" class="btn btn-primary btn-circle edit" title="Editar plano"
                                        data-toggle="tooltip" data-placement="top">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>
                                    @endcan
                                    @can('Excluir planos')
                                        <a href="{{ route('dashboard.plan.destroy', $plan->id) }}" class="btn btn-danger btn-circle" title="Excluir plano"
                                           data-toggle="tooltip"
                                           data-placement="top"
                                           data-method="DELETE"
                                           data-confirm-title="Por favor confirme"
                                           data-confirm-text="Tem certeza que deseja excluir esse plano?"
                                           data-confirm-delete="Sim">
                                            <i class="glyphicon glyphicon-trash"></i>
                                        </a>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                            @else
                            <tr>
                                <td colspan="6" class="text-center"><em>Não foram encontrados registros</em></td>
                            </tr>
                            @endif
                        </tbody>
                    </table>
                    <div class="text-center">
                        {{ $plans->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('js')
    <script src="{{ asset('js/delete.handler.js') }}"></script>
@stop