routes/web.php
    Route::post('anuncio/{id}/pagar', ['as' => 'advertisement.plan.pay','uses' => 'AdvertisementController@pagar']);
    Route::get('checkout/sucesso', ['as' => 'checkout.sucess','uses' => 'PagseguroController@checkoutSuccess']);

    Route::get('minha-conta/mensagens', ['as' => 'message.index','uses' => 'MessagesController@index']);
    Route::get('minha-conta/mensagens/{id}', ['as' => 'message.show','uses' => 'MessagesController@show']);
    Route::post('mensagens/{id}/send', ['as' => 'message.send','uses' => 'MessagesController@send']);
    Route::get('minha-conta/mensagens/{id}/excluir', ['as' => 'conversation.delete','uses' => 'MessagesController@delete']);

    Route::post('avaliar/artista/{id}', ['as' => 'review.artist.store','uses' => 'AdvertisementController@storeReviewArtista']);
    Route::post('avaliar/profissional/{id}', ['as' => 'review.professional.store','uses' => 'AdvertisementController@storeReviewProfessional']);
    Route::get('avaliacao/{id}/excluir', ['as' => 'review.delete','uses' => 'AdvertisementController@deleteReview']);

    Route::get('minha-conta', ['as' => 'myaccount.index','uses' => 'MyAccountController@index']);
    Route::get('minha-conta/anuncios', ['as' => 'myaccount.advertisement','uses' => 'MyAccountController@advertisement']);
    Route::get('minha-conta/anuncios/{anuncio_id}/editar', ['as' => 'myaccount.advertisement.edit','uses' => 'MyAccountController@advertisementEdit']);
    Route::post('minha-conta/anuncios/{anuncio_id}/editar', ['as' => 'myaccount.advertisement.update','uses' => 'MyAccountController@advertisementUpdate']);
    Route::get('minha-conta/anuncios/{anuncio_id}/publicar', ['as' => 'myaccount.advertisement.publish','uses' => 'MyAccountController@advertisementPublish']);
    Route::post('minha-conta/anuncios/{anuncio_id}/editar/imagem', ['as' => 'myaccount.advertisement.update.image','uses' => 'MyAccountController@advertisementUpdateImage']);
    Route::get('minha-conta/anuncios/{anuncio_id}/pagar', ['as' => 'myaccount.advertisement.pay','uses' => 'MyAccountController@advertisementPay']);
    Route::get('minha-conta/anuncios/{anuncio_id}/excluir', ['as' => 'myaccount.advertisement.delete','uses' => 'MyAccountController@advertisementDelete']);
    Route::get('minha-conta/configuracoes', ['as' => 'myaccount.settings','uses' => 'MyAccountController@settings']);
    Route::post('minha-conta/configuracoes/editar', ['as' => 'myaccount.settings.update.details','uses' => 'MyAccountController@settingsupdate']);
    Route::post('minha-conta/configuracoes/editar/senha', ['as' => 'myaccount.settings.update.password','uses' => 'MyAccountController@settingsupdatepassword']);
    Route::get('minha-conta/plano', ['as' => 'myaccount.plan','uses' => 'MyAccountController@plan']);
    Route::get('minha-conta/plano/{id}/assinar', ['as' => 'myaccount.plan.subscribe','uses' => 'MyAccountController@planSubscribe']);
    Route::post('minha-conta/plano/{id}/assinar', ['as' => 'myaccount.plan.subscribe.post','uses' => 'MyAccountController@planSubscribePost']);
    Route::get('minha-conta/plano/cancelar', ['as' => 'myaccount.plan.cancel','uses' => 'MyAccountController@planCancel']);
    Route::get('minha-conta/pagamentos', ['as' => 'myaccount.payments','uses' => 'MyAccountController@payments']);
});

Route::group(['middleware' => ['auth','role:Administrador|Gerente|Proprietário'],'prefix' => 'dashboard', 'as' => 'dashboard.'], function() {
    Route::get('/', ['as' => 'index','uses' => 'Dashboard\DashboardController@index']);

    Route::get('profile', ['as' => 'profile','uses' => 'Dashboard\ProfileController@index']);
    Route::post('profile/details/update', ['as' => 'profile.update.details','uses' => 'Dashboard\ProfileController@updateDetails']);
    Route::post('profile/login-details/update', ['as' => 'profile.update.login-details','uses' => 'Dashboard\ProfileController@updateLoginDetails']);

    Route::get('user', ['as' => 'user.list','uses' => 'Dashboard\UsersController@index']);
    Route::get('user/create', ['as' => 'user.create','uses' => 'Dashboard\UsersController@create']);
    Route::post('user/create', ['as' => 'user.store','uses' => 'Dashboard\UsersController@store']);
    Route::get('user/{user_id}/edit', ['as' => 'user.edit','uses' => 'Dashboard\UsersController@edit']);
    Route::post('user/{user_id}/update/details', ['as' => 'user.update.details','uses' => 'Dashboard\UsersController@updateDetails']);
    Route::post('user/{user_id}/update/login-details', ['as' => 'user.update.login-details','uses' => 'Dashboard\UsersController@updateLoginDetails']);      //----------testar
    Route::post('user/{user_id}/update/role', ['as' => 'user.update.role','uses' => 'Dashboard\UsersController@updateRole']);
    Route::post('user/{user_id}/update/permissions', ['as' => 'user.update.permission','uses' => 'Dashboard\UsersController@updatePermissions']);
    Route::post('user/{user_id}/update/plan', ['as' => 'user.update.plan','uses' => 'Dashboard\UsersController@updatePlan']);
    Route::post('user/{user_id}/update/plan/days/add', ['as' => 'user.update.plan.days.add','uses' => 'Dashboard\UsersController@updatePlanDaysAdd']);
    Route::post('user/{user_id}/update/plan/days/remove', ['as' => 'user.update.plan.days.remove','uses' => 'Dashboard\UsersController@updatePlanDaysRemove']);
    Route::delete('user/{user_id}/delete', ['as' => 'user.delete','uses' => 'Dashboard\UsersController@destroy']);

    Route::get('advertisement', ['as' => 'advertisement.list','uses' => 'Dashboard\AdvertisementsController@index']);
    Route::get('advertisement/create', ['as' => 'advertisement.create','uses' => 'Dashboard\AdvertisementsController@create']);
    Route::post('advertisement/store', ['as' => 'advertisement.store','uses' => 'Dashboard\AdvertisementsController@store']);
    Route::get('advertisement/{advertisement_id}/edit', ['as' => 'advertisement.edit','uses' => 'Dashboard\AdvertisementsController@edit']);
    Route::post('advertisement/{advertisement_id}/update', ['as' => 'advertisement.update','uses' => 'Dashboard\AdvertisementsController@update']);
    Route::post('advertisement/{advertisement_id}/update-image', ['as' => 'advertisement.updateimage','uses' => 'Dashboard\AdvertisementsController@updateImage']);
    Route::delete('advertisement/{advertisement_id}/delete', ['as' => 'advertisement.destroy','uses' => 'Dashboard\AdvertisementsController@destroy']);

    Route::get('payment', ['as' => 'payment.list','uses' => 'Dashboard\PaymentsController@index']);
    Route::get('payment/{payment_id}', ['as' => 'payment.show','uses' => 'Dashboard\PaymentsController@show']);

    Route::get('musicstyle', ['as' => 'musicstyle.list','uses' => 'Dashboard\MusicStylesController@index']);
    Route::get('musicstyle/create', ['as' => 'musicstyle.create','uses' => 'Dashboard\MusicStylesController@create']);
    Route::post('musicstyle/store', ['as' => 'musicstyle.store','uses' => 'Dashboard\MusicStylesController@store']);
    Route::get('musicstyle/{musicstyle_id}/edit', ['as' => 'musicstyle.edit','uses' => 'Dashboard\MusicStylesController@edit']);
    Route::post('musicstyle/{musicstyle_id}/update', ['as' => 'musicstyle.update','uses' => 'Dashboard\MusicStylesController@update']);
    Route::delete('musicstyle/{musicstyle_id}/delete', ['as' => 'musicstyle.destroy','uses' => 'Dashboard\MusicStylesController@destroy']);

    Route::get('category', ['as' => 'category.list','uses' => 'Dashboard\CategoriesController@index']);
    Route::get('category/create', ['as' => 'category.create','uses' => 'Dashboard\CategoriesController@create']);
    Route::post('category/store', ['as' => 'category.store','uses' => 'Dashboard\CategoriesController@store']);
    Route::get('category/{category_id}/edit', ['as' => 'category.edit','uses' => 'Dashboard\CategoriesController@edit']);
    Route::post('category/{category_id}/update', ['as' => 'category.update','uses' => 'Dashboard\CategoriesController@update']);
    Route::delete('category/{category_id}/delete', ['as' => 'category.destroy','uses' => 'Dashboard\CategoriesController@destroy']);

    Route::get('review', ['as' => 'review.list','uses' => 'Dashboard\ReviewsController@index']);
    Route::get('review/{review_id}/edit', ['as' => 'review.edit','uses' => 'Dashboard\ReviewsController@edit']);
    Route::post('review/{review_id}/update', ['as' => 'review.update','uses' => 'Dashboard\ReviewsController@update']);
    Route::delete('review/{review_id}/delete', ['as' => 'review.destroy','uses' => 'Dashboard\ReviewsController@destroy']);


    Route::get('plan', ['as' => 'plan.list','uses' => 'Dashboard\PlansController@index']);
    Route::get('plan/create', ['as' => 'plan.create','uses' => 'Dashboard\PlansController@create']);
    Route::post('plan/store', ['as' => 'plan.store','uses' => 'Dashboard\PlansController@store']);
    Route::get('plan/{plan_id}/edit', ['as' => 'plan.edit','uses' => 'Dashboard\PlansController@edit']);
    Route::post('plan/{plan_id}/update', ['as' => 'plan.update','uses' => 'Dashboard\PlansController@update']);
    Route::delete('plan/{plan_id}/delete', ['as' => 'plan.destroy','uses' => 'Dashboard\PlansController@destroy']);

    Route::get('role', ['as' => 'role.index','uses' => 'Dashboard\RolesController@index']);
    Route::get('role/create', ['as' => 'role.create','uses' => 'Dashboard\RolesController@create']);
    Route::post('role/store', ['as' => 'role.store','uses' => 'Dashboard\RolesController@store']);
    Route::get('role/{role_id}/edit', ['as' => 'role.edit','uses' => 'Dashboard\RolesController@edit']);
    Route::post('role/{role_id}/update', ['as' => 'role.update','uses' => 'Dashboard\RolesController@update']);
    Route::delete('role/{role_id}/delete', ['as' => 'role.delete','uses' => 'Dashboard\RolesController@destroy']);

    Route::get('permission', ['as' => 'permission.index','uses' => 'Dashboard\PermissionsController@index']);

app/Http/Controllers/Dashboard/AdvertisementsController.php
<?php

namespace App\Http\Controllers\Dashboard;


use App\Http\Requests\dashboard\advertisement\UpdateAdvertisementImageRequest;
use App\Http\Requests\dashboard\advertisement\UpdateAdvertisementRequest;
use App\Http\Requests\dashboard\category\CreateCategoryRequest;
use App\Http\Requests\dashboard\category\UpdateCategoryRequest;
use App\Models\Advertisement;
use App\Models\Category;
use App\Models\Cidade;
use App\Models\Estado;
use App\Models\MusicStyle;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;


class AdvertisementsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::user()->can('Visualizar anúncios')){
            return redirect()->back();
        }
        $peer_page = 15;
        $search = Input::get('search');
        $type = Input::get('tipo');
        $advertisements = Advertisement::Query();
        if ($search <> "") {
            $advertisements->orwhereHas('user', function (Builder $query) use ($search) {
                $query->where('email', 'like', "%{$search}%");
            });
            $advertisements->orwhereHasMorph('embedded','*', function (Builder $query) use ($search) {
                $query->where('title', 'like', "%{$search}%");
            });
            $advertisements->orwhereHasMorph('embedded','*', function (Builder $query) use ($search) {
                $query->where('description', 'like', "%{$search}%");
            });
        }
        if($type <> ""){
            if($type==1){
                $advertisements->Artist();
            }elseif($type==2){
                $advertisements->Professional();
            }

        }
        $advertisements = $advertisements->paginate($peer_page);
        if ($search) {
            $advertisements->appends(['search' => $search]);
        }
        if ($type) {
            $advertisements->appends(['tipo' => $type]);
        }

        return view('dashboard.advertisement.list', compact('advertisements'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $permission_id
     * @return \Illuminate\Http\Response
     */
    public function edit($advertisement_id)
    {
        if(!Auth::user()->can('Editar anúncios')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $edit = true;
        $advertisement = Advertisement::find($advertisement_id);
        if($advertisement->embedded_type=="App\Models\Artist"){
            $estilos=MusicStyle::all();
            $estados = Estado::all();
            $cidades=Cidade::where('estado_id','=',$advertisement->estado_id)->get();

            return view('dashboard.advertisement.edit',compact('edit', 'advertisement','estilos',
                'estados','cidades'));
        }else{
            $categorias = Category::All();
            $subcategorias = Category::where('parent_id','=',$advertisement->embedded->category_id)->get();
            $estados = Estado::all();
            $cidades=Cidade::where('estado_id','=',$advertisement->estado_id)->get();

            return view('dashboard.advertisement.edit',compact('edit', 'advertisement',
                'estados','cidades','categorias','subcategorias'));
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAdvertisementRequest $request, $advertisement_id)
    {
        if(!Auth::user()->can('Editar anúncios')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $advertisement = Advertisement::find($advertisement_id);
        $advertisement->estado_id = $request->estado;
        $advertisement->cidade_id = $request->cidade;
        $advertisement->save();

        if($advertisement->embedded_type=="App\Models\Artist"){
            $embedded = $advertisement->embedded;
            $embedded->title = $request->title;
            $embedded->description = $request->description;
            $embedded->cache = $request->cache;
            $embedded->video = $request->videoyoutube;
            $embedded->facebook = $request->facebook;
            $embedded->instagram = $request->instagram;
            $embedded->youtube = $request->youtube;
            $embedded->save();
            $embedded->musicalstyles()->sync($request->estilos);
        }else{
            $embedded = $advertisement->embedded;
            $embedded->title = $request->title;
            $embedded->description = $request->description;
            $embedded->category_id = $request->categoria;
            $embedded->subcategory_id = $request->subcategoria;
            $embedded->facebook = $request->facebook;
            $embedded->instagram = $request->instagram;
            $embedded->youtube = $request->youtube;
            $embedded->save();
        }


        return redirect()->back()->withSuccess('Anúncio atualizado com sucesso!');
    }

    public function updateImage(UpdateAdvertisementImageRequest $request, $advertisement_id)
    {
        if(!Auth::user()->can('Editar anúncios')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $advertisement = Advertisement::find($advertisement_id);
        $embedded = $advertisement->embedded;
        $aux = $embedded->imagepath;
        $file = Input::file('foto');
        $path = '';
        if($file){
            $path = Storage::disk('public_uploads')->put('/', $file);
        }
        $embedded->imagepath = $path;
        $embedded->save();
        Storage::disk('public_uploads')->delete($aux);

        return redirect()->back()->withSuccess('Anúncio atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($advertisement_id)
    {
        if(!Auth::user()->can('Excluir anúncios')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $advertisement = Advertisement::find($advertisement_id);
        $advertisement->delete();

        return redirect()->route('dashboard.advertisement.list')->withSuccess('Anúncio excluido com sucesso!');
    }
}

resources/views/dashboard/permission/add.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Adicionar permissão')

@section('content_header')
    <h1>
        Criar nova permissão
        <small>Detalhes da permissão</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li>Permissões</li>
        <li class="active">Criar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')
@can('Criar permissões')
    <form action="{{route('dashboard.permission.store')}}" method="post">
        @csrf
        <div class="row">
            <div class="col-md-8">
                @include('dashboard.permission.partials.details', ['edit' => false])
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-save"></i>
                    Criar permissão
                </button>
            </div>
        </div>
    </form>
@endcan
@stop

resources/views/dashboard/permission/edit.blade.php
@extends('dashboard.layouts.master')

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
@endsection

@section('page-title', 'Editar permissão')

@section('content_header')
    <h1>
        {{ $permission->name }}
        <small>editar detalhes da permissão</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li>Permissões</li>
        <li class="active">Editar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')

<div class="nav-tabs-custom">
    <!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#details" aria-controls="details" role="tab" data-toggle="tab">
            <i class="glyphicon glyphicon-th"></i>
            Detalhes
        </a>
    </li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="details">
        <div class="row">
            <div class="col-lg-8 col-md-7">
                @can('Editar permissões')
                    <form action="{{route('dashboard.permission.update',$permission->id)}}" method="post">
                    @csrf
                    @include('dashboard.permission.partials.details')
                    </form>
                @endcan
            </div>
        </div>
    </div>
</div>
</div>

@stop

@section('js')
@stop

resources/views/dashboard/permission/list.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Permissões')
@section('content_header')
<h1>
    Permissões
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Permissões</li>
</ol>
@endsection
@section('content')
@include('partials.messages')

<div class="row tab-search">
    <div class="col-md-2 col-xs-2">
        @can('Criar permissões')
        <a href="{{ route('dashboard.permission.create') }}" class="btn btn-success" id="add-user">
            <i class="glyphicon glyphicon-plus"></i>
            Adicionar permissão
        </a>
        @endcan
    </div>
    <div class="col-md-5 col-xs-3"></div>
    <form method="GET" action="" accept-charset="UTF-8" id="link-form">
        <div class="col-md-3 col-xs-4">
            <div class="input-group custom-search-form">
                <input type="text" class="form-control" name="search" value="{{ app('request')->input('search') }}" placeholder="Procure por permissões...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="search-users-btn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                    @if (app('request')->input('search') != '')
                        <a href="{{ route('dashboard.permission.index') }}" class="btn btn-danger" type="button" >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    @endif
                </span>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Lista de permissões cadastradas</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div id="users-table-wrapper">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <th>Nome</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            @if (count($permissions))
                            @foreach ($permissions as $permission)
                            <tr>
                                <td>{{ $permission->name }}</td>
                                <td class="text-center">
                                    @can('Editar permissões')
                                    <a href="{{ route('dashboard.permission.edit', $permission->id) }}" class="btn btn-primary btn-circle edit" title="Editar permissão"
                                        data-toggle="tooltip" data-placement="top">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>
                                    @endcan
                                    @can('Excluir permissões')
                                    <a href="{{ route('dashboard.permission.destroy', $permission->id) }}" class="btn btn-danger btn-circle" title="Excluir permissão"
                                        data-toggle="tooltip"
                                        data-placement="top"
                                        data-method="DELETE"
                                        data-confirm-title="Por favor confirme"
                                        data-confirm-text="Tem certeza que deseja excluir essa permissão?"
                                        data-confirm-delete="Sim">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                            @else
                            <tr>
                                <td colspan="6" class="text-center"><em>Não foram encontrados registros</em></td>
                            </tr>
                            @endif
                        </tbody>
                    </table>
                    <div class="text-center">
                        {{ $permissions->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('js')
    <script src="{{ asset('js/delete.handler.js') }}"></script>
@stop